package dev.rushii.rgp.toolchains

import dev.rushii.rgp.AndroidDeclaration
import dev.rushii.rgp.GenerateAndroidToolchainsTask
import java.io.File

internal interface ToolchainInfo {
	/**
	 * A cargo triple as defined [here](https://doc.rust-lang.org/nightly/rustc/platform-support.html).
	 */
	val cargoTarget: String

	companion object {
		/**
		 * Obtain platform specific toolchain info for a specific Cargo target.
		 * @param targetName A cargo triple as defined [here](https://doc.rust-lang.org/nightly/rustc/platform-support.html).
		 * @param android The Android config to be used for a specific project (required only for Android targets).
		 * 				  This config should be fully configured, meaning initializing [ToolchainInfo] should not be done at configuration time.
		 * @param androidNdkInfo The Android NDK used in the Gradle project (required only for Android targets).
		 * @param androidCustomToolchainsDir If [AndroidDeclaration.usePrebuiltToolchain] is false, then this specifies the location
		 * 									at which the custom toolchains are generated by the [GenerateAndroidToolchainsTask] from the NDK
		 * 									specified by [androidNdkInfo] (required only for Android targets).
		 */
		fun getForCargoTarget(
			targetName: String,
			android: AndroidDeclaration? = null,
			androidNdkInfo: AndroidNdkInfo? = null,
			androidCustomToolchainsDir: File? = null,
		): ToolchainInfo {
			// Likely requires the Android NDK for compilation.
			if (targetName.contains("android")) {
				val androidConfig = android ?: throw IllegalArgumentException("Android config required for an Android target")
				val ndk = androidNdkInfo ?: throw IllegalArgumentException("NDK info required for an Android target")
				return AndroidToolchainInfo(targetName, androidConfig, ndk, androidCustomToolchainsDir)
			}

			// Unknown, assumed will build correctly
			return NativeToolchainInfo(cargoTarget = targetName)
		}
	}
}
